fix: support token with space like `Bearer xxxxx`
I guess, having token like `Bearer xxxx` is the cause of an error like

```sh
-- Running release-plz release --
error: unexpected argument '***' found

Usage: release-plz release [OPTIONS]

For more information, try '--help'.
```